=== pawelmaslanka/FlexConfig/schema_reference.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Router",
    "description": "Router configuration",
    "type": "object",
    "properties": {
        "platform": {
            "description": "Platform configuration",
            "type": "object",
            "properties": {
                "port": {
                    "type": "object",
                    "maxProperties": 64,
                    "patternProperties": {
                        "^eth-(6[5-6])|eth-(6[0-6]|5[0-9]|4[0-9]|3[0-9]|2[0-9]|1[0-9]|[1-9])$": {
                            "type": "object",
                            "properties": {
                                "breakout-mode": {
                                    "enum": ["none", "4x100G"],
                                    "default": "none",
                                    "update-constraints": [
                                        "if (xpath_value('/platform/port[@key]/breakout-mode') <> 'none') then must(exists(xpath_key_based('/interface/ethernet[@key]', '/platform/port[@key]')) == false)",
                                        "if (xpath_value('/platform/port[@key]/breakout-mode') == 'none') then must(exists(xpath_match_regex('/interface/ethernet[@key]', '/interface/ethernet/*', '^eth-(6[5-6])|eth-(6[0-6]|5[0-9]|4[0-9]|3[0-9]|2[0-9]|1[0-9]|[1-9])(_[1-4])?$')) == false)"
                                    ],
                                    "action": {
                                        "on-update-path": "/update",
                                        "on-delete-path": "/delete",
                                        "server-address": "127.0.0.1:8000"
                                    }
                                }
                            },
                            "required": [
                                "breakout-mode"
                            ],
                            "additionalProperties": false
                        }
                    },
                    "additionalProperties": false
                }
            },
            "required": [
                "port"
            ],
            "additionalProperties": false
        },
        "interface": {
            "description": "Interface configuration",
            "type": "object",
            "properties": {
                "ethernet": {
                    "description": "Ethernet interfaces collection",
                    "type": "object",
                    "maxProperties": 64,
                    "patternProperties": {
                        "^eth-(6[5-6])|eth-(6[0-6]|5[0-9]|4[0-9]|3[0-9]|2[0-9]|1[0-9]|[1-9])$": {
                            "description": "Main interface configuration",
                            "type": "object",
                            "properties": {
                                "speed": {
                                    "description": "Interface speed",
                                    "enum": ["100G", "400G"],
                                    "default": "400G",
                                    "action": {
                                        "on-update-path": "/update",
                                        "server-address": "127.0.0.1:8000"
                                    }
                                }
                            },
                            "additionalProperties": false,
                            "action": {
                                "on-update-path": "/update",
                                "on-delete-path": "/delete",
                                "server-address": "127.0.0.1:8000"
                            },
                            "update-dependencies": [
                                "/platform/port[@key]/breakout-mode"
                            ],
                            "delete-dependencies": [
                                "/interface/aggregate-ethernet",
                                "/vlan"
                            ],
                            "update-constraints": [
                                "must(xpath_value('/platform/port[@key]/breakout-mode') == 'none')"
                            ]
                        },
                        "^eth-(6[5-6])|eth-(6[0-6]|5[0-9]|4[0-9]|3[0-9]|2[0-9]|1[0-9]|[1-9])(_[1-4])$": {
                            "description": "Sub-interface configuration",
                            "type": "object",
                            "properties": {

                            },
                            "additionalProperties": false,
                            "action": {
                                "on-update-path": "/update",
                                "on-delete-path": "/delete",
                                "server-address": "127.0.0.1:8000"
                            },
                            "update-dependencies": [
                                "/platform/port[@key]/breakout-mode"
                            ],
                            "update-constraints": [
                                "must(xpath_value_key_regex_replace('/platform/port[@key]/breakout-mode', '^eth-(6[5-6])|eth-(6[0-6]|5[0-9]|4[0-9]|3[0-9]|2[0-9]|1[0-9]|[1-9])') <> 'none')"
                            ]
                        }
                    },
                    "additionalProperties": false
                },
                "aggregate-ethernet": {
                    "description": "Aggregate Ethernet Interfaces collection",
                    "type": "object",
                    "uniqueItems": true,
                    "maxProperties": 32,
                    "patternProperties": {
                        "^ae-(6[5-6])|ae-(6[0-6]|5[0-9]|4[0-9]|3[0-9]|2[0-9]|1[0-9]|[1-9])$": {
                            "type": "object",
                            "properties": {
                                "members": {
                                    "description": "Members of Aggregate Interface",
                                    "type": "object",
                                    "patternProperties": {
                                        "^eth-(6[5-6])|eth-(6[0-6]|5[0-9]|4[0-9]|3[0-9]|2[0-9]|1[0-9]|[1-9])(_[1-4])?$": {
                                            "type": "null",
                                            "additionalProperties": false,
                                            "reference": [
                                                "/interface/ethernet/@"
                                            ],
                                            "action": {
                                                "on-update-path": "/update",
                                                "on-delete-path": "/delete",
                                                "server-address": "127.0.0.1:8000"
                                            },
                                            "update-dependencies": [
                                                "/interface/ethernet[@key]"
                                            ],
                                            "update-constraints": [
                                                "must(exists(xpath(@)))"
                                            ]
                                        }
                                    },
                                    "additionalProperties": false
                                },
                                "control-protocol": {
                                    "description": "Control protocol",
                                    "enum": ["none", "lacp"],
                                    "default": "none"
                                }
                            },
                            "additionalProperties": false,
                            "action": {
                                "on-update-path": "/update",
                                "on-delete-path": "/delete",
                                "server-address": "127.0.0.1:8000"
                            },
                            "delete-constraints": [
                                "must(count(xpath('/interface/aggregate-ethernet[@key]/members')) == 0)"
                            ]
                        }
                    },
                    "additionalProperties": false
                }
            },
            "required": [
            ],
            "additionalProperties": false
        },
        "vlan": {
            "description": "VLAN configuration",
            "type": "object",
            "properties": {
                "id": {
                    "type": "object",
                    "uniqueItems": true,
                    "maxProperties": 4095,
                    "description": "VLANs collection",
                    "patternProperties": {
                        "^((40[0-9][0-5])|([1-3][0-9][0-9][0-9])|([0-9][0-9])|[1-9])$": {
                            "type": "object",
                            "properties": {
                                "members": {
                                    "description": "Members of VLAN",
                                    "type": "object",
                                    "patternProperties": {
                                        "^eth-(6[5-6])|eth-(6[0-6]|5[0-9]|4[0-9]|3[0-9]|2[0-9]|1[0-9]|[1-9])(_[1-4])?$": {
                                            "type": "null",
                                            "additionalProperties": false,
                                            "reference": [
                                                "/interface/ethernet/@"
                                            ],
                                            "update-dependencies": [
                                                "/interface/ethernet[@key]"
                                            ],
                                            "update-constraints": [
                                                "must(exists(xpath(@)))"
                                            ],
                                            "action": {
                                                "on-update-path": "/update",
                                                "on-delete-path": "/delete",
                                                "server-address": "127.0.0.1:8000"
                                            }
                                        },
                                        "^ae-(6[5-6])|ae-(6[0-6]|5[0-9]|4[0-9]|3[0-9]|2[0-9]|1[0-9]|[1-9])$": {
                                            "type": "null",
                                            "additionalProperties": false,
                                            "reference": [
                                                "/interface/aggregate-ethernet/@"
                                            ],
                                            "update-dependencies": [
                                                "/interface/aggregate-ethernet[@key]/members"
                                            ],
                                            "update-constraints": [
                                                "must(exists(xpath(@)))"
                                            ],
                                            "action": {
                                                "on-update-path": "/update",
                                                "on-delete-path": "/delete",
                                                "server-address": "127.0.0.1:8000"
                                            }
                                        }
                                    },
                                    "additionalProperties": false
                                }
                            },
                            "additionalProperties": false,
                            "action": {
                                "on-update-path": "/update",
                                "on-delete-path": "/delete",
                                "server-address": "127.0.0.1:8000"
                            },
                            "delete-constraints": [
                                "must(count(xpath('/vlan/id[@key]/members')) == 0)"
                            ]
                        }
                    },
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        },
        "protocol": {
            "description": "Protocol configuration",
            "type": "object",
            "properties": {
                "lldp": {
                    "type": "object"
                }
            },
            "additionalProperties": false
        }
    },
    "required": [
        "platform",
        "interface",
        "vlan",
        "protocol"
    ],
    "additionalProperties": false
}

=== pawelmaslanka/FlexConfig/config_reference.json
{
    "interface": {
        "ethernet": {
            "eth-1": {
                "speed": "100G"
            }
        },
        "aggregate-ethernet": {}
    },
    "vlan": {
        "id": {
            "2": {
                "members": {
                    "eth-1": null
                }
            }
        }
    },
    "protocol": {
        
    },
    "platform": {
        "port": {
            "eth-1": {
                "breakout-mode": "none"
            }
        }
    }
}

=== pawelmaslanka/FlexConfig/config_test.json
{
    "interface": {
        "aggregate-ethernet": {},
        "ethernet": {
            "eth-1": {
                "speed": "100G"
            },
            "eth-2": {
                "speed": "100G"
            }
        }
    },
    "platform": {
        "port": {
            "eth-1": {
                "breakout-mode": "none"
            },
            "eth-2": {
                "breakout-mode": "none"
            }
        }
    },
    "protocol": {},
    "vlan": {
        "id": {
            "2": {
                "members": {
                    "eth-1": null,
                    "eth-2": null
                }
            }
        }
    }
}
